[package]
name = "ars_parallel_apex"
version = "0.1.0"
edition = "2021"

[lib]
name = "ars_parallel_apex"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
rayon = "1.10"
ars_native = { path = "../ars_gen_3_apex_baseline" }
pyo3 = { version = "0.23.0", features = ["extension-module", "abi3-py310"] }
